### ISSUE TITLE
NullPointerException of mValidationContext

### ISSUE THREAD

**Issue by edwardaa** [ragunathjawahar/android-saripaar#101]
I am using saripaar `v2.0.0`, an exception ocurrs since `mValidationContext` was not instantiated:
```
Caused by: java.lang.NullPointerException
  at com.mobsandgeeks.saripaar.Validator.createRulesSafelyAndLazily(Validator.java:460)
  at com.mobsandgeeks.saripaar.Validator.put(Validator.java:401)
```
Consider following example without annotated fields:
```java
private TextView textView;
private Validator validator;

@Override
public void onCreate(Bundle savedInstanceState) {
    super.onCreate();

    textView = findViewById(R.id.text);
    validator = new Validator(this);
    validator.put(textView, new QuickRule<TextView>() {
        @Override
        public boolean isValid(TextView view) {
            return false;
        }

        @Override
        public String getMessage(Context context) {
            return null;
        }
    });
}
```

**Comment by ragunathjawahar** [comment]
@edwardaa Thanks for reporting this.

**Comment by ragunathjawahar** [comment]
`2.0.2` released to Maven Central, should be available in a couple of hours.

**Comment by edwardaa** [comment]
Thanks for your hard work! it works like a charm

**Comment by ragunathjawahar** [comment]
You're welcome :)
