### ISSUE TITLE
Is it possible to work with two separate Validators? 

### ISSUE THREAD

**Issue by Kikju** [ragunathjawahar/android-saripaar#104]
Hi,
I have a question. Is it possible to work with two separate Validators, which each has own rules to cover.

My case:
I have layout with form and send button. I want, that send button will be enable/disable according to validation state of form. But not all rules (given by anotation) but just for example NotEmpty. So it is possible to create two validators, first will do just enable/disable send button based on one rule (for example when all views are not empty) and second one will do classical validation work with all anotations and showing errors.

Thanks for you answers

**Comment by ragunathjawahar** [comment]
Hi, it is possible to use two different validator. But you should have them in two different classes. Let's just say that we have two forms on the same screen. A login form and a registration form.

1. Create two Form classes - `RegistrationForm` and a `LoginForm`.
2. `RegistrationForm` should contain fields for registration and `LoginForm` should contain fields for logging in.
3. Add two different validators to these classes, add appropriate methods for getting / setting data / triggering validation, etc.,

This should work. Let me know if you have any more questions. Here's a [SO Post](http://stackoverflow.com/questions/31794392/saripaar-validation-android-multiple-forms/31880126#31880126) that gives you the rough outline of the code.

**Comment by Kikju** [comment]
At first, I was thinking that you talking about two separate forms instead of two separate validators but when I thought about it.. I relase that you are right: It is basically the same situation and I need to create virtually two validators on two forms which have references to the same form...
Here is basics of my implementation:

    public class LoginActivity extends ActionBarActivity {
    
        private EditText username;
        private EditText password;
        private Button loginButton;
    
        private EnableDisableButtonValidator enableDisableButtonValidator;
        private LoginValidator loginValidator;
    
        @Override
        protected void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            
            //...
    
            username = (LabeledEditText) findViewById(R.id.username);
            password = (LabeledEditText) findViewById(R.id.password);
            loginButton = (Button) findViewById(R.id.login);
    
            enableDisableButtonValidator = new EnableDisableButtonValidator(username, password, new Validator.ValidationListener() {
                @Override
                public void onValidationSucceeded() {
                    loginButton.setEnabled(true);
                }
    
                @Override
                public void onValidationFailed(List<ValidationError> errors) {
                    loginButton.setEnabled(false);
                }
            });
    
            loginValidator = new LoginValidator(username, password, new Validator.ValidationListener() {
                @Override
                public void onValidationSucceeded() {
                    //DO SOMETHING 
                }
    
                @Override
                public void onValidationFailed(List<ValidationError> errors) {
                    //SHOW ERROR
                }
            });
    
            TextWatcher watcher = new TextWatcher() {
                @Override
                public void beforeTextChanged(CharSequence s, int start, int count, int after) {
                }
    
                @Override
                public void onTextChanged(CharSequence s, int start, int before, int count) {
                }
    
                @Override
                public void afterTextChanged(Editable s) {
                    enableDisableButtonValidator.validate();
                }
            };
    
            username.addTextChangedListener(watcher);
            password.addTextChangedListener(watcher);

            loginButton.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    loginValidator.validate();
                }
            });
        }
    
        class EnableDisableButtonValidator {
    
            @NotEmpty
            private EditText username;
            @NotEmpty
            private EditText password;
    
            private Validator validator;
    
            public EnableDisableButtonValidator(EditText username, EditText password, Validator.ValidationListener listener) {
                this.username = username;
                this.password = password;
                validator = new Validator(this);
                validator.setValidationListener(listener);
            }
    
            public void validate() {
                validator.validate();
            }
        }
    
        class LoginValidator {
    
            @Email
            private EditText username;
            @Password
            private EditText password;
    
            private Validator validator;
    
            public LoginValidator(EditText username, EditText password, Validator.ValidationListener listener) {
                this.username = username;
                this.password = password;
                validator = new Validator(this);
                validator.setValidationListener(listener);
            }
    
            public void validate() {
                validator.validate();
            }
        }
    }


Thanks very much, it works perfectly

**Comment by ragunathjawahar** [comment]
You nailed it! You're welcome.

**Comment by arjunkn** [comment]
Hi, I am getting this error when using this code...

FATAL EXCEPTION: main
                                                                        Process: com.xx.xx, PID: 24281
                                                                        java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mobsandgeeks.saripaar.ValidationContext.setViewRulesMap(java.util.Map)' on a null object reference
                                                                            at com.mobsandgeeks.saripaar.Validator.createRulesSafelyAndLazily(Validator.java:479)
                                                                            at com.mobsandgeeks.saripaar.Validator.validate(Validator.java:330)
                                                                            at com.mobsandgeeks.saripaar.Validator.validate(Validator.java:295)
                                                                            at com.xx.xx.MerchantMyAccountActivity$EditAccountValidator.validate(MerchantMyAccountActivity.java:179)
                                                                            at com.xx.xx.MerchantMyAccountActivity$2.onClick(MerchantMyAccountActivity.java:126)
                                                                            at android.view.View.performClick(View.java:4756)
                                                                            at com.balysv.materialripple.MaterialRippleLayout$PerformClickEvent.run(MaterialRippleLayout.java:648)
                                                                            at com.balysv.materialripple.MaterialRippleLayout$3.onAnimationEnd(MaterialRippleLayout.java:336)
                                                                            at android.animation.AnimatorSet$AnimatorSetListener.onAnimationEnd(AnimatorSet.java:829)
                                                                            at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1089)
                                                                            at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:666)
                                                                            at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:682)
                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                            at android.view.Choreographer.doFrame(Choreographer.java:549)
                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
