### ISSUE TITLE
"'EditText loginText' is null" error

### ISSUE THREAD

**Issue by Qazzaq2** [ragunathjawahar/android-saripaar#113]
Hi,
I get error message "'EditText loginText' is null"  when i try to validate fields. Whats wrong is with my code? 

    public class LoginActivity extends AppCompatActivity implements ValidationListener {

    @NotEmpty
    EditText loginText;
    @Password(min = 3, scheme = Password.Scheme.ALPHA_NUMERIC_MIXED_CASE_SYMBOLS)
    EditText passwordText;
    Button loginButton;

    

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_login);
        loginButton = (Button) findViewById(R.id.loginButton);
        final Validator validator = new Validator(LoginActivity.this);
        validator.setValidationListener(LoginActivity.this);

        loginButton.setOnClickListener(new View.OnClickListener() {

            @Override
            public void onClick(View v) {
                validator.validate();
                login(v);
            }
        });

    }
       @Override
    public void onValidationSucceeded() {
        Toast.makeText(LoginActivity.this, "Yay! we got it right!", Toast.LENGTH_SHORT).show();
    }

    @Override
    public void onValidationFailed(List<ValidationError> errors) {
        for (ValidationError error : errors) {
            View view = error.getView();
            String message = error.getCollatedErrorMessage(this);

            // Display error messages
            if (view instanceof EditText) {
                ((EditText) view).setError(message);
            } else {
                Toast.makeText(LoginActivity.this, message, Toast.LENGTH_LONG).show();
            }
        }
    }

**Comment by Kikju** [comment]
you are missing findViewById statement loginText and  passwordText
Dňa 19.9.2015 10:01 používateľ "Qazzaq2" <notifications@github.com> napísal:

**Comment by Qazzaq2** [comment]
Im still getting the same error

**Comment by ragunathjawahar** [comment]
Can you post the updated code?

**Comment by Qazzaq2** [comment]
XML files seems ok, traceroute:

            FATAL EXCEPTION: main
            java.lang.IllegalStateException: 'EditText loginText' is null.
            at com.mobsandgeeks.saripaar.Validator.getView(Validator.java:667)
            at com.mobsandgeeks.saripaar.Validator.createRules(Validator.java:580)
            at com.mobsandgeeks.saripaar.Validator.createRulesSafelyAndLazily(Validator.java:478)
            at com.mobsandgeeks.saripaar.Validator.validate(Validator.java:330)
            at com.mobsandgeeks.saripaar.Validator.validate(Validator.java:295)
            at com.example.studio.cribs.spontan.LoginActivity$3.onClick(LoginActivity.java:102)
            at android.view.View.performClick(View.java:4101)
            at android.view.View$PerformClick.run(View.java:17087)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4849)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by ragunathjawahar** [comment]
Set a break point and try to find out why `loginText` and `passwordText` is `null` or post your XML and Java sources.
