### ISSUE TITLE
Multiple form validations in one acitvity

### ISSUE THREAD

**Issue by arjunkn** [ragunathjawahar/android-saripaar#134]
Hi, 

I have 3 forms and 3 submit buttons in one activity and i want to validate them separately. I tried the answer in issue #104 but I am getting this error when using that code...
```
FATAL EXCEPTION: main
Process: com.xx.xx, PID: 24281
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mobsandgeeks.saripaar.ValidationContext.setViewRulesMap(java.util.Map)' on a null object reference
at com.mobsandgeeks.saripaar.Validator.createRulesSafelyAndLazily(Validator.java:479)
at com.mobsandgeeks.saripaar.Validator.validate(Validator.java:330)
at com.mobsandgeeks.saripaar.Validator.validate(Validator.java:295)
at com.xx.xx.MerchantMyAccountActivity$EditAccountValidator.validate(MerchantMyAccountActivity.java:179)
at com.xx.xx.MerchantMyAccountActivity$2.onClick(MerchantMyAccountActivity.java:126)
at android.view.View.performClick(View.java:4756)
at com.balysv.materialripple.MaterialRippleLayout$PerformClickEvent.run(MaterialRippleLayout.java:648)
at com.balysv.materialripple.MaterialRippleLayout$3.onAnimationEnd(MaterialRippleLayout.java:336)
at android.animation.AnimatorSet$AnimatorSetListener.onAnimationEnd(AnimatorSet.java:829)
at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1089)
at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:666)
at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:682)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
at android.view.Choreographer.doCallbacks(Choreographer.java:580)
at android.view.Choreographer.doFrame(Choreographer.java:549)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5221)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by gauravsak** [comment]
@arjunkn Please post some code.

Your form validation depends on where you call `Validator.validate()`.

**Comment by arjunkn** [comment]
Thanks for the reply, This how I initialized 

  merchantEditAccountValidator = new MerchantEditAccountValidator(etContactNumber, etShopName, etContactPerson, btnEditAccount);

        editAccountValidator = new EditAccountValidator(etContactNumber, etShopName, etContactPerson, new Validator.ValidationListener() {
            @Override
            public void onValidationSucceeded() {
//                editAccount();
            }

            @Override
            public void onValidationFailed(List<ValidationError> errors) {
                for (ValidationError error : errors) {
                    View view = error.getView();
                    String message = error.getCollatedErrorMessage(activity);

                    if (view instanceof EditText) {
                        ((EditText) view).setError(message);
                    }
                }
            }
        });

and called in button click

btnEditAccount.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                editAccountValidator.validate();
              
            }
        });

**Comment by gauravsak** [comment]
@arjunkn What is the difference between `MerchantEditAccountValidator` and `EditAccountValidator`? Could you post the code which shows use of multiple forms please? Thanks.

**Comment by arjunkn** [comment]
sry first line is commented, 

this is second form calling.

         editPasswordValidator = new EditPasswordValidator(etOldPassword, etNewPassword,                     etRetypeNewPassword, new Validator.ValidationListener() {
            @Override
            public void onValidationSucceeded() {
        //                editPassword();
            }

            @Override
            public void onValidationFailed(List<ValidationError> errors) {
                for (ValidationError error : errors) {
                    View view = error.getView();
                    String message = error.getCollatedErrorMessage(activity);

                    // Display error messages ;)
                    if (view instanceof EditText) {
                        ((EditText) view).setError(message);
                    }
                }
            }
        });

below is the validation class.

     class EditAccountValidator {

        @NonNull
        private EditText etContactNumber;

        @NonNull
        private EditText etShopName;

        @NonNull
        private EditText etContactPerson;

        private Validator validator;

        public EditAccountValidator(EditText etContactNumber, EditText etShopName, EditText etContactPerson, Validator.ValidationListener validationListener) {
            this.etContactNumber = etContactNumber;
            this.etShopName = etShopName;
            this.etContactPerson = etContactPerson;

            validator = new Validator(this);
            validator.setValidationListener(validationListener);
        }

        public void validate() {
            Utils.println("val: " + validator);
            validator.validate();
        }
    }

**Comment by ragunathjawahar** [comment]
Use 3 different form controller classes to group views and then validate them.
