### ISSUE TITLE
Proguard - ViewDataAdapter - getData returns Object

### ISSUE THREAD

**Issue by Nasca91** [ragunathjawahar/android-saripaar#142]
Hi, here is my ViewDataAdapter for TextInputLayout View.

```
public class TextInputLayoutAdapter implements ViewDataAdapter<TextInputLayout, String> {
    @Override
    public String getData(TextInputLayout view) throws ConversionException {
        return view.getEditText().getText().toString();
    }
}
```

It works well in Debug mode but in Release, with Proguard, I have an UnsupportedOperationException caused by the ViewDataAdapter.

Can someone help me?

Thanks in advance.

**Comment by ragunathjawahar** [comment]
A complete stack trace would be helpful.

**Comment by Nasca91** [comment]
Here it is:
```
03-01 08:39:47.990 5734-6076/it.quok E/AndroidRuntime: FATAL EXCEPTION: main
                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{it.quok/it.quok.activities.RegistrationActivity_}: java.lang.UnsupportedOperationException: To use 'com.mobsandgeeks.saripaar.annotation.NotEmpty' on 'android.support.design.widget.TextInputLayout', register a 'com.mobsandgeeks.saripaar.adapter.ViewDataAdapter' that returns a 'java.lang.String' from the 'android.support.design.widget.TextInputLayout'.
                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2332)
                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2368)
                                                           at android.app.ActivityThread.access$600(ActivityThread.java:151)
                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1330)
                                                           at android.os.Handler.dispatchMessage(Handler.java:99)
                                                           at android.os.Looper.loop(Looper.java:155)
                                                           at android.app.ActivityThread.main(ActivityThread.java:5536)
                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                           at java.lang.reflect.Method.invoke(Method.java:511)
                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1074)
                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:841)
                                                           at dalvik.system.NativeStart.main(Native Method)
                                                        Caused by: java.lang.UnsupportedOperationException: To use 'com.mobsandgeeks.saripaar.annotation.NotEmpty' on 'android.support.design.widget.TextInputLayout', register a 'com.mobsandgeeks.saripaar.adapter.ViewDataAdapter' that returns a 'java.lang.String' from the 'android.support.design.widget.TextInputLayout'.
                                                           at com.mobsandgeeks.saripaar.Validator.getRuleAdapterPair(Validator.java:586)
                                                           at com.mobsandgeeks.saripaar.Validator.createRules(Validator.java:555)
                                                           at com.mobsandgeeks.saripaar.Validator.createRulesSafelyAndLazily(Validator.java:459)
                                                           at com.mobsandgeeks.saripaar.Validator.put(Validator.java:401)
                                                           at it.quok.activities.cn.a(RegistrationActivity.java:219)
                                                           at it.quok.activities.RegistrationActivity_.a(RegistrationActivity_.java:117)
                                                           at org.a.a.b.c.a(OnViewChangedNotifier.java:41)
                                                           at it.quok.activities.RegistrationActivity_.setContentView(RegistrationActivity_.java:49)
                                                           at it.quok.activities.RegistrationActivity_.onCreate(RegistrationActivity_.java:39)
                                                           at android.app.Activity.performCreate(Activity.java:5066)
                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1102)
                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2288)
                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2368) 
                                                           at android.app.ActivityThread.access$600(ActivityThread.java:151) 
                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1330) 
                                                           at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                           at android.os.Looper.loop(Looper.java:155) 
                                                           at android.app.ActivityThread.main(ActivityThread.java:5536) 
                                                           at java.lang.reflect.Method.invokeNative(Native Method) 
                                                           at java.lang.reflect.Method.invoke(Method.java:511) 
                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1074) 
                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:841) 
                                                           at dalvik.system.NativeStart.main(Native Method) 
```
Thanks for the reply.

**Comment by ragunathjawahar** [comment]
Did you register your adapter by calling `validator.registerAdapter(TextInputLayout.class, new TextInputLayoutAdapter())`?

**Comment by Nasca91** [comment]
Yep:
```
TextInputLayoutAdapter textInputLayoutAdapter = new TextInputLayoutAdapter();
formValidator.registerAdapter(TextInputLayout.class, textInputLayoutAdapter);
```
I read that there are problems with anonymous DataAdapter in `registerAdapter` method.

**Comment by ragunathjawahar** [comment]
Hmmm... with Google bringing in the Jack compiler I think this needs to be fixed. I'll give it some thought and get back on this.

**Comment by ragunathjawahar** [comment]
Try excluding your adapter from obfuscation.

**Comment by mathieusachet** [comment]
Hi, I've the same problem here. It works in debug but proguard in release, returns same error than @Ciano91.

**Comment by sosite** [comment]
I have the same problem. @ragunathjawahar hint helped me so thanks 😉 

My proguard config (for saripaar) now looks like:
```
-keep class com.mobsandgeeks.saripaar.** {*;}
-keep @com.mobsandgeeks.saripaar.annotation.ValidateUsing class * {*;}
-keep class com.your.package.validation.TextInputLayoutDataAdapter {*;} #YOU MUST TO ADD THIS!
```

**Comment by rjoncontract** [comment]
This is a ProGuard configuration issue. Will take care of this by automatically excluding data adapters in the next release.

**Comment by ravidsrk** [comment]
@sosite  I am also facing the same issue. 
I tried adding 
```
-keep class com.mobsandgeeks.saripaar.** {*;}
-keep @com.mobsandgeeks.saripaar.annotation.ValidateUsing class * {*;}
-keep class com.your.package.validation.TextInputLayoutDataAdapter {*;}
```
Still facing the same issue.

 @ragunathjawahar @rjoncontract Any updates on this issues?

**Comment by sosite** [comment]
@ravidsrk Hah, I hope that you change `com.your.package.validation` to your package name? 😉

**Comment by ravidsrk** [comment]
@sosite Offcourse i have the package name :) 
`-keep class com.example.android.utils.TextInputLayoutAdapter {*;}`

**Comment by xcesco** [comment]
I have the same problem and I found this thread only after I resolve my problem. My solution is on Proguard configuration too, but it's more generic, because I leave untouched ALL the class that implements `ViewDataAdapter`.

```
# validation https://github.com/ragunathjawahar/android-saripaar
-keepattributes *Annotation*
-keep class com.mobsandgeeks.saripaar.** {*;}
-keep @com.mobsandgeeks.saripaar.annotation.ValidateUsing class * {*;}
-keepclassmembers class * implements com.mobsandgeeks.saripaar.adapter.ViewDataAdapter {*;}
```

I hope it helps someone :)

**Comment by PhanPirang** [comment]
> I have the same problem and I found this thread only after I resolve my problem. My solution is on Proguard configuration too, but it's more generic, because I leave untouched ALL the class that implements `ViewDataAdapter`.
> 
> ```
> # validation https://github.com/ragunathjawahar/android-saripaar
> -keepattributes *Annotation*
> -keep @interface com.mobsandgeeks.saripaar.annotation.*
> -keep class com.mobsandgeeks.saripaar.** {*;}
> -keep @com.mobsandgeeks.saripaar.annotation.ValidateUsing class * {*;}
> -keepclasseswithmembers class * {  @com.mobsandgeeks.saripaar.annotation.* <fields>;}
> -keepclassmembers class * {  @com.mobsandgeeks.saripaar.annotation.* *;}
> -keepclassmembers class * implements com.mobsandgeeks.saripaar.adapter.ViewDataAdapter {*;}
> ```
> 
> I hope it helps someone and that you can close this issue :)

You saved my life :D
