### ISSUE TITLE
Error in  custom rule on proguard

### ISSUE THREAD

**Issue by sunil19822701** [ragunathjawahar/android-saripaar#148]
I have created my custom rule for validating field if isn't empty
here is custom rule code
code for class http://pastebin.com/FMhwCzAD
code for interface http://pastebin.com/NSs92LAw
activity code http://pastebin.com/pKJHphMv
proguard rules 

```
#Android Saripaar
-keep class com.mobsandgeeks.saripaar.**
-keep class com.mobsandgeeks.saripaar.** {*;}
```

if i keep pro guard disable it works fine on proguard 
I am getting error the following error 

```
 Caused by: com.mobsandgeeks.saripaar.exception.SaripaarViolationException: Unable to find a matching adapter for `c.s.s.ssacct.CustomRules.OptionalAddressRule`, that returns a `java.lang.Object`.
    at com.mobsandgeeks.saripaar.Registry.register(SourceFile:100)
    at com.mobsandgeeks.saripaar.Validator.registerAnnotation(SourceFile:190)
    at c.s.s.ssacct.Actvities.AddParty.k(SourceFile:149)
    at c.s.s.ssacct.Actvities.AddParty_.a(SourceFile:117)
    at org.androidannotations.api.b.c.a(SourceFile:41)
    at c.s.s.ssacct.Actvities.AddParty_.setContentView(SourceFile:54)
    at c.s.s.ssacct.Actvities.AddParty_.onCreate(SourceFile:44)
    at android.app.Activity.performCreate(Activity.java:6251)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2504) 
    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:148) 
    at android.app.ActivityThread.main(ActivityThread.java:5449) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114) 
```

**Comment by amanthaIsuru** [comment]
Hope you are building the signed apk and minfiy the project in the android manifest. When you are minifying the project it can't identify the custom classes you have created. The cause is  you have used the OptionalAddressRule.class file directly somewhere in your code. So in the proguard you have to eliminating the custome classes by using this 

-keep class <your custom class>.** { *; }
